// ─────────────────────────────────────────────
//  ALEJANDRO ARAB — CMS DE PROYECTOS
//  Editá este archivo para actualizar el sitio.
//  imageAfter: URL de imagen que aparece DESPUÉS de esa sección
//  imageAfter: null → no hay imagen después de esa sección
// ─────────────────────────────────────────────

// Resolve local asset paths regardless of whether we're at root or works/
const _BASE = window.location.pathname.includes('/works/') ? '../' : '';
function _asset(path) { return path.startsWith('http') ? path : _BASE + path; }

const PROJECTS = [
  {
    id: 'fan-raise',
    num: '01',
    title: 'Fan Raise',
    subtitle:   'Web & Mobile App for Sports-Based Fundraising',
    subtitleEs: 'Aplicación Web y Móvil para Recaudación de Fondos a través del Deporte',
    category:   'Product Design · Sports Tech · Fundraising',
    categoryEs: 'Diseño de Producto · Tecnología Deportiva · Fundraising',
    client: 'FanRaise',
    type:   'Web & Mobile App',
    typeEs: 'App Web y Móvil',
    duration: '~4 months',
    durationEs: '~4 meses',
    status: 'Completed',
    tag: 'Sports Tech',
    tagHighlight: true,
    cover: _asset('assets/works/fanraise/01.png'),
    thumb: _asset('assets/covers/fanraise.png'),
    sections: [
      {
        label: null, labelEs: null,
        text: 'FanRaise is a web and mobile platform that enables nonprofit organizations to raise funds through sports engagement. Fans participate by making pledge-based donations tied to predictions about sports events. If the prediction is correct, the user fulfills their pledge and can participate in prize draws or rewards. The platform connects organizations, athletes, teams, and fans in an experience that blends sports entertainment with social impact.',
        textEs: 'FanRaise es una plataforma web y móvil que permite a organizaciones sin fines de lucro recaudar fondos a través del engagement deportivo. Los fans participan haciendo donaciones basadas en predicciones sobre eventos deportivos. Si la predicción es correcta, el usuario cumple su compromiso y puede participar en sorteos o recompensas. La plataforma conecta organizaciones, atletas, equipos y fans en una experiencia que combina entretenimiento deportivo con impacto social.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I led the full product design process from early strategic discussions to high-fidelity prototypes. The goal was to create a simple experience that combines sports predictions, donations, and gamification. I also designed the visual identity and logo of the product, aligning the brand with the emotional and participatory tone of the experience. Flows were designed both for fans participating in events and for organizations creating fundraising campaigns.',
        textEs: 'Lideré el proceso completo de diseño de producto, desde las primeras discusiones estratégicas hasta los prototipos de alta fidelidad. El objetivo era crear una experiencia simple que combinara predicciones deportivas, donaciones y gamificación. También diseñé la identidad visual y el logo del producto, alineando la marca con el tono emocional y participativo de la experiencia. Los flujos fueron diseñados tanto para fans que participan en eventos como para organizaciones que crean campañas de recaudación.',
        imageAfter: _asset('assets/works/fanraise/02.png'),
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The vision was to transform how fans support social causes by leveraging the excitement of sports. Instead of passive donations, users actively participate by predicting sports outcomes. This creates a more engaging and emotional fundraising experience that connects entertainment with social impact.',
        textEs: 'La visión era transformar la manera en que los fans apoyan causas sociales aprovechando la emoción del deporte. En lugar de donaciones pasivas, los usuarios participan activamente prediciendo resultados deportivos. Esto crea una experiencia de recaudación más atractiva y emocional que conecta el entretenimiento con el impacto social.',
        imageAfter: _asset('assets/works/fanraise/03.png'),
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'One of the main challenges was designing a system that combines multiple mechanics: sports predictions, pledge donations, rewards, and event management. The interface needed to keep the experience simple while supporting these complex interactions.',
        textEs: 'Uno de los principales desafíos fue diseñar un sistema que combina múltiples mecánicas: predicciones deportivas, donaciones comprometidas, recompensas y gestión de eventos. La interfaz necesitaba mantener la experiencia simple mientras soportaba estas interacciones complejas.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Nonprofit organizations often struggle to maintain long-term donor engagement. Traditional fundraising campaigns rely on direct donations that can feel passive to younger audiences. FanRaise addresses this by turning donations into an interactive experience tied to sports events.',
        textEs: 'Las organizaciones sin fines de lucro suelen tener dificultades para mantener el engagement de los donantes a largo plazo. Las campañas de recaudación tradicionales dependen de donaciones directas que pueden resultar pasivas para audiencias más jóvenes. FanRaise aborda esto convirtiendo las donaciones en una experiencia interactiva vinculada a eventos deportivos.',
        imageAfter: _asset('assets/works/fanraise/04.png'),
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'Users can explore sports events, select a prediction, and choose a pledge donation amount. If the prediction is correct, the pledged donation is completed. Organizations and teams can create events, define participation rules, and monitor results through dedicated dashboards.',
        textEs: 'Los usuarios pueden explorar eventos deportivos, seleccionar una predicción y elegir un monto de donación comprometida. Si la predicción es correcta, la donación comprometida se completa. Las organizaciones y equipos pueden crear eventos, definir reglas de participación y monitorear resultados a través de paneles dedicados.',
        imageAfter: _asset('assets/works/fanraise/05.png'),
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'The result was a fully designed web and mobile platform for sports-based fundraising. Product flows include event discovery, predictions, donations, and campaign management. The project demonstrates how sports engagement can create new forms of social participation and fundraising.',
        textEs: 'El resultado fue una plataforma web y móvil completamente diseñada para recaudación de fondos a través del deporte. Los flujos del producto incluyen descubrimiento de eventos, predicciones, donaciones y gestión de campañas. El proyecto demuestra cómo el engagement deportivo puede crear nuevas formas de participación social y recaudación de fondos.',
        imageAfter: _asset('assets/works/fanraise/06.png'),
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Brand Identity'],
    deliverablesEs: ['Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Prototipo', 'Sistema de diseño', 'Identidad de marca'],
    prev: null,
    next: 'rockmap',
  },
  {
    id: 'rockmap',
    num: '02',
    title: 'RockMap',
    subtitle:   'Mobile App for Discovering Rock Culture Across Europe',
    subtitleEs: 'App Móvil para Descubrir Cultura Rock en Europa',
    category:   'Mobile Product Design · Music Discovery · Social',
    categoryEs: 'Diseño de Producto Móvil · Descubrimiento Musical · Social',
    client: 'Concept Project',
    type:   'iOS & Android App',
    typeEs: 'App iOS & Android',
    duration: '2024',
    durationEs: '2024',
    status: 'Completed',
    tag: 'Mobile',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/hFrX1T4nGkqzEovF9bhl1fjyqE8.png',
    sections: [
      {
        label: null, labelEs: null,
        text: 'Rockmap is a mobile app designed for rock fans traveling across Europe who want to discover bars, concerts, and music venues. The platform combines travel, music discovery, and community into a unique cultural experience.',
        textEs: 'Rockmap es una app móvil diseñada para fans del rock que viajan por Europa y quieren descubrir bares, conciertos y locales de música. La plataforma combina viaje, descubrimiento musical y comunidad en una experiencia cultural única.',
        imageAfter: 'https://framerusercontent.com/images/hFrX1T4nGkqzEovF9bhl1fjyqE8.png',
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'The product experience was centered around a map interface for discovering music venues and fans nearby. The design prioritized discovery, simplicity, and community — building a sense of belonging around shared musical passion.',
        textEs: 'La experiencia del producto se centró en una interfaz de mapa para descubrir locales musicales y fans cercanos. El diseño priorizó el descubrimiento, la simplicidad y la comunidad, creando un sentido de pertenencia alrededor de la pasión musical compartida.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'To combine travel, music, and community into a unique discovery experience. The vision was to create the definitive guide to rock culture in Europe — a living map built and maintained by the community.',
        textEs: 'Combinar viaje, música y comunidad en una experiencia de descubrimiento única. La visión era crear la guía definitiva de la cultura rock en Europa: un mapa vivo construido y mantenido por la comunidad.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'Integrating Spotify data, events, and geolocation into a cohesive experience. The main challenge was balancing the complexity of a map-based interface with the simplicity required for a community app.',
        textEs: 'Integrar datos de Spotify, eventos y geolocalización en una experiencia cohesiva. El principal desafío fue equilibrar la complejidad de una interfaz basada en mapas con la simplicidad requerida para una app comunitaria.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Travelers rely on fragmented sources to discover local music experiences. There was no single platform connecting rock culture, venues, and fans across European cities.',
        textEs: 'Los viajeros dependen de fuentes fragmentadas para descubrir experiencias musicales locales. No existía una plataforma única que conectara la cultura rock, los locales y los fans en las ciudades europeas.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The app allows users to explore venues, artists, and community through a map-centered interface. Users can discover local scenes, follow artists, and connect with other rock fans in the same city.',
        textEs: 'La app permite a los usuarios explorar locales, artistas y comunidad a través de una interfaz centrada en el mapa. Los usuarios pueden descubrir escenas locales, seguir artistas y conectarse con otros fans del rock en la misma ciudad.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'A complete mobile product concept for location-based music discovery was designed. The product was built with scalability in mind, supporting multiple cities and countries while maintaining a consistent community feel.',
        textEs: 'Se diseñó un concepto completo de producto móvil para el descubrimiento musical basado en ubicación. El producto fue construido pensando en la escalabilidad, con soporte para múltiples ciudades y países manteniendo una identidad comunitaria coherente.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['UX Research', 'Wireframes', 'Mobile UI', 'Prototype', 'Design System'],
    deliverablesEs: ['Investigación UX', 'Wireframes', 'UI Móvil', 'Prototipo', 'Sistema de diseño'],
    prev: 'fan-raise',
    next: 'tickit-clubes',
  },
  {
    id: 'tickit-clubes',
    num: '03',
    title: 'Tickit Clubes',
    subtitle:   'Digital Membership and Ticketing Platform for Sports Clubs',
    subtitleEs: 'Plataforma Digital de Membresías y Tickets para Clubes Deportivos',
    category:   'Product Design · Sports Tech · Ticketing',
    categoryEs: 'Diseño de Producto · Tecnología Deportiva · Ticketing',
    client: 'Tickit',
    type:   'Web & Mobile Platform',
    typeEs: 'Plataforma Web y Móvil',
    duration: '2024–2025',
    durationEs: '2024–2025',
    status: 'Completed',
    tag: 'Sports Tech',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/YjO3t9fDkTY1CzeU93Be7O5iqw.png',
    sections: [
      {
        label: null, labelEs: null,
        text: 'Tickit Clubes is a platform designed for sports clubs that digitalizes membership management, ticket sales, and exclusive content. It enables clubs to manage members, sell tickets, and offer digital benefits through a centralized experience. The solution combines ticketing, digital identity, and content into a single platform accessible via mobile or web.',
        textEs: 'Tickit Clubes es una plataforma diseñada para clubes deportivos que digitaliza la gestión de membresías, venta de tickets y contenido exclusivo. Permite a los clubes gestionar socios, vender entradas y ofrecer beneficios digitales a través de una experiencia centralizada. La solución combina ticketing, identidad digital y contenido en una sola plataforma accesible vía móvil o web.',
        imageAfter: 'https://framerusercontent.com/images/YjO3t9fDkTY1CzeU93Be7O5iqw.png',
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I designed the full product experience including user flows, mobile and web UI, digital membership systems, and event management. The goal was to create a flexible platform adaptable to different clubs while maintaining identity and customization.',
        textEs: 'Diseñé la experiencia completa del producto, incluyendo flujos de usuario, UI móvil y web, sistemas de membresía digital y gestión de eventos. El objetivo era crear una plataforma flexible adaptable a diferentes clubes manteniendo identidad y personalización.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The vision was to transform the relationship between clubs and fans through a unified digital experience combining membership, content, and events. Moving from physical cards and manual processes to a fully digital ecosystem.',
        textEs: 'La visión era transformar la relación entre los clubes y sus fans a través de una experiencia digital unificada que combine membresías, contenido y eventos. Pasar de tarjetas físicas y procesos manuales a un ecosistema completamente digital.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'A key challenge was adapting a general ticketing platform to the specific needs of sports clubs, including customization, identity, and content management. Designing for two very different user types — administrators and fans — within a single coherent product.',
        textEs: 'Un desafío clave fue adaptar una plataforma de ticketing general a las necesidades específicas de los clubes deportivos, incluyendo personalización, identidad y gestión de contenido. Diseñar para dos tipos de usuario muy diferentes — administradores y fans — dentro de un producto coherente.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Clubs often manage memberships, ticketing, and fan communication through disconnected systems. This fragmentation leads to poor fan experience and operational inefficiency.',
        textEs: 'Los clubes suelen gestionar membresías, ticketing y comunicación con los fans a través de sistemas desconectados. Esta fragmentación lleva a una mala experiencia para el hincha e ineficiencia operativa.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'Users can access their digital membership, purchase tickets, explore exclusive content, and manage their relationship with the club from a single app. Club administrators get a dedicated dashboard to manage operations independently.',
        textEs: 'Los usuarios pueden acceder a su membresía digital, comprar entradas, explorar contenido exclusivo y gestionar su relación con el club desde una sola app. Los administradores del club cuentan con un panel dedicado para gestionar las operaciones de forma independiente.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'A modular platform was designed enabling clubs to digitalize their ecosystem and enhance fan experience. The product was adopted by multiple clubs across Latin America.',
        textEs: 'Se diseñó una plataforma modular que permite a los clubes digitalizar su ecosistema y mejorar la experiencia del hincha. El producto fue adoptado por múltiples clubes en Latinoamérica.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['Product Strategy', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Design System'],
    deliverablesEs: ['Estrategia de producto', 'Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Sistema de diseño'],
    prev: 'rockmap',
    next: 'tickit',
  },
  {
    id: 'tickit',
    num: '04',
    title: 'Tickit',
    subtitle:   'Event Ticketing Platform for General and Sports Events',
    subtitleEs: 'Plataforma de Ticketing para Eventos Generales y Deportivos',
    category:   'Product Design · Event Tech · Ticketing',
    categoryEs: 'Diseño de Producto · Tecnología de Eventos · Ticketing',
    client: 'Tickit',
    type:   'Web & Mobile Platform',
    typeEs: 'Plataforma Web y Móvil',
    duration: '2024–2025',
    durationEs: '2024–2025',
    status: 'Completed',
    tag: 'Ticketing',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/FATuDnHFj0egSso4TOCh8lBTWo.png',
    sections: [
      {
        label: null, labelEs: null,
        text: 'Tickit is a digital ticketing platform designed to manage events of all kinds, from concerts to sports events. It allows organizers to create, manage, and sell tickets while users can discover events and purchase tickets easily.',
        textEs: 'Tickit es una plataforma de ticketing digital diseñada para gestionar eventos de todo tipo, desde conciertos hasta eventos deportivos. Permite a los organizadores crear, gestionar y vender entradas, mientras que los usuarios pueden descubrir eventos y comprar entradas fácilmente.',
        imageAfter: 'https://framerusercontent.com/images/FATuDnHFj0egSso4TOCh8lBTWo.png',
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I designed the full product experience including user flows, UI, event management system, and the visual identity and branding of the product. The approach centered around reducing steps from event discovery to ticket purchase while building trust through transparent pricing.',
        textEs: 'Diseñé la experiencia completa del producto, incluyendo flujos de usuario, UI, sistema de gestión de eventos e identidad visual y branding. El enfoque se centró en reducir los pasos desde el descubrimiento del evento hasta la compra de la entrada, generando confianza mediante precios transparentes.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'To create a scalable platform that simplifies event management and enhances the ticket purchasing experience. The vision was to make ticketing feel as fast and intuitive as the best consumer apps.',
        textEs: 'Crear una plataforma escalable que simplifique la gestión de eventos y mejore la experiencia de compra de entradas. La visión era hacer que el ticketing se sienta tan rápido e intuitivo como las mejores apps de consumo.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'The main challenge was designing a flexible experience that works across different event types while maintaining simplicity and speed. The system needed to handle high-traffic moments — popular events that sell out in minutes.',
        textEs: 'El principal desafío fue diseñar una experiencia flexible que funcione para distintos tipos de eventos manteniendo simplicidad y velocidad. El sistema debía manejar momentos de alto tráfico: eventos populares que se agotan en minutos.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Many ticketing systems are complex and unintuitive for both organizers and users. Hidden fees and friction in the purchase flow cause drop-offs and poor fan experience.',
        textEs: 'Muchos sistemas de ticketing son complejos y poco intuitivos tanto para organizadores como para usuarios. Las tarifas ocultas y la fricción en el flujo de compra generan abandono y una mala experiencia.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The platform allows users to explore events, purchase tickets, and manage access easily, while providing organizers with tools to manage events, track sales, and engage fans.',
        textEs: 'La plataforma permite a los usuarios explorar eventos, comprar entradas y gestionar el acceso fácilmente, mientras proporciona a los organizadores herramientas para gestionar eventos, seguir las ventas y conectar con los fans.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'A complete ticketing platform was designed with a focus on usability, scalability, and consistent branding. The product was launched and used for multiple sporting and entertainment events across Latin America.',
        textEs: 'Se diseñó una plataforma de ticketing completa con foco en usabilidad, escalabilidad y branding consistente. El producto fue lanzado y utilizado en múltiples eventos deportivos y de entretenimiento en Latinoamérica.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Brand Identity'],
    deliverablesEs: ['Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Prototipo', 'Sistema de diseño', 'Identidad de marca'],
    prev: 'tickit-clubes',
    next: 'thinknube-ai',
  },
  {
    id: 'thinknube-ai',
    num: '05',
    title: 'Thinknube.AI',
    subtitle:   'AI-Powered Market Research SaaS Platform',
    subtitleEs: 'Plataforma SaaS de Investigación de Mercado con IA',
    category:   'AI Product Design · SaaS · Market Research',
    categoryEs: 'Diseño de Producto con IA · SaaS · Investigación de Mercado',
    client: 'Nube Research',
    type:   'SaaS Web Application',
    typeEs: 'Aplicación Web SaaS',
    duration: '~4 months',
    durationEs: '~4 meses',
    status: 'Completed',
    tag: 'AI',
    tagHighlight: true,
    cover: _asset('assets/works/thinknube/01.png'),
    sections: [
      {
        label: null, labelEs: null,
        text: 'ThinkNube is an AI-powered market research SaaS platform developed by Nube Research. The platform allows companies to create conversational research studies using an AI agent that interviews participants through channels such as WhatsApp, Instagram, or direct links. The product automates processes that traditionally require research agencies, manual interviews, and long analysis cycles. Teams can design studies, reach participants, and analyze insights within a single platform.',
        textEs: 'ThinkNube es una plataforma SaaS de investigación de mercado con IA, desarrollada por Nube Research. La plataforma permite a las empresas crear estudios de investigación conversacionales usando un agente de IA que entrevista participantes a través de canales como WhatsApp, Instagram o enlaces directos. El producto automatiza procesos que tradicionalmente requieren agencias de investigación, entrevistas manuales y largos ciclos de análisis. Los equipos pueden diseñar estudios, llegar a participantes y analizar insights dentro de una sola plataforma.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'The approach focused on balancing AI automation with a clear and intuitive user experience. Product flows were designed for study creation, audience segmentation, and insights analysis. I worked on product architecture, study creation flows, dashboard design, and the overall visual direction of the platform.',
        textEs: 'El enfoque se centró en equilibrar la automatización de la IA con una experiencia de usuario clara e intuitiva. Se diseñaron flujos de producto para la creación de estudios, segmentación de audiencias y análisis de insights. Trabajé en la arquitectura del producto, flujos de creación de estudios, diseño del dashboard y la dirección visual general de la plataforma.',
        imageAfter: _asset('assets/works/thinknube/02.png'),
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The vision was to democratize access to market research, enabling companies of any size to gather real user insights quickly without relying on traditional agencies. The design focused on clarity, professionalism, and trust while maintaining the simplicity of a modern SaaS platform.',
        textEs: 'La visión era democratizar el acceso a la investigación de mercado, permitiendo a empresas de cualquier tamaño recopilar insights reales de usuarios rápidamente sin depender de agencias tradicionales. El diseño se enfocó en claridad, profesionalismo y confianza, manteniendo la simplicidad de una plataforma SaaS moderna.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'A key challenge was structuring complex research parameters such as segmentation, quotas, and response validation into a simple configuration flow. The platform needed to manage multiple variables within a single experience without overwhelming users.',
        textEs: 'Un desafío clave fue estructurar parámetros de investigación complejos como segmentación, cuotas y validación de respuestas en un flujo de configuración simple. La plataforma necesitaba gestionar múltiples variables dentro de una sola experiencia sin abrumar a los usuarios.',
        imageAfter: _asset('assets/works/thinknube/03.png'),
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Companies often rely on expensive research agencies or data-only tools that lack real interaction with consumers. ThinkNube addresses this by combining artificial intelligence with real consumer interviews.',
        textEs: 'Las empresas suelen depender de agencias de investigación costosas o herramientas solo de datos que carecen de interacción real con los consumidores. ThinkNube aborda esto combinando inteligencia artificial con entrevistas reales a consumidores.',
        imageAfter: _asset('assets/works/thinknube/04.png'),
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'Users can define objectives, select audiences, configure parameters, and monitor responses in real time. Quality control tools help detect unreliable answers. The system also includes response quality monitoring and analytics dashboards.',
        textEs: 'Los usuarios pueden definir objetivos, seleccionar audiencias, configurar parámetros y monitorear respuestas en tiempo real. Las herramientas de control de calidad ayudan a detectar respuestas poco confiables. El sistema también incluye monitoreo de calidad de respuestas y dashboards de analíticas.',
        imageAfter: _asset('assets/works/thinknube/05.png'),
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'The result was a solid MVP of an AI-powered research platform capable of automating interviews and generating structured insights. The product combines automation with a human-centered approach, using AI to facilitate research while preserving real consumer feedback.',
        textEs: 'El resultado fue un MVP sólido de una plataforma de investigación con IA capaz de automatizar entrevistas y generar insights estructurados. El producto combina automatización con un enfoque centrado en el ser humano, usando IA para facilitar la investigación mientras preserva el feedback real de los consumidores.',
        imageAfter: _asset('assets/works/thinknube/06.png'),
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['Product Strategy', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Design System', 'Prototype'],
    deliverablesEs: ['Estrategia de producto', 'Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Sistema de diseño', 'Prototipo'],
    prev: 'tickit',
    next: 'brikka',
  },
  {
    id: 'brikka',
    num: '06',
    title: 'Brikka',
    subtitle:   'Web3 Real Estate Tokenization Platform',
    subtitleEs: 'Plataforma Web3 de Tokenización Inmobiliaria',
    category:   'Web3 Product Design · Fintech · Real Estate',
    categoryEs: 'Diseño Web3 · Fintech · Real Estate',
    client:   'Real Estate Development Company',
    type:   'Web3 Platform',
    typeEs: 'Plataforma Web3',
    duration: '~3 months',
    durationEs: '~3 meses',
    status: 'Completed',
    tag: 'Web3',
    tagHighlight: true,
    cover: _asset('assets/works/brikka/01.png'),
    sections: [
      {
        label: null, labelEs: null,
        text: 'Brikka is a blockchain-based platform that enables tokenization of real estate projects. It connects developers seeking funding with investors who want to participate through digital assets. Users can invest in different components of a construction project represented as tokens, allowing participation with different levels of capital.',
        textEs: 'Brikka es una plataforma basada en blockchain que permite la tokenización de proyectos inmobiliarios. Conecta desarrolladores que buscan financiamiento con inversores que quieren participar a través de activos digitales. Los usuarios pueden invertir en distintos componentes de un proyecto de construcción representados como tokens, permitiendo la participación con diferentes niveles de capital.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'The full product experience was designed including the landing page, investor platform, and project management dashboard. The goal was to structure complex processes — token creation, investment simulation, and wallet management — into an intuitive and understandable experience.',
        textEs: 'Se diseñó la experiencia completa del producto, incluyendo la landing page, la plataforma de inversores y el panel de gestión de proyectos. El objetivo era estructurar procesos complejos —creación de tokens, simulación de inversiones y gestión de billetera— en una experiencia intuitiva y comprensible.',
        imageAfter: _asset('assets/works/brikka/02.png'),
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The goal was to democratize real estate investing by allowing participation with smaller capital through tokenization. The design focused on communicating security, transparency, and control over investments.',
        textEs: 'El objetivo era democratizar la inversión inmobiliaria permitiendo la participación con menor capital a través de la tokenización. El diseño se centró en comunicar seguridad, transparencia y control sobre las inversiones.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'A major challenge was integrating decentralized wallets and multiple token types into clear investment flows. The system needed to manage multiple token types associated with different parts of each real estate project while supporting investment flows connected to decentralized wallets.',
        textEs: 'Un gran desafío fue integrar billeteras descentralizadas y múltiples tipos de tokens en flujos de inversión claros. El sistema debía gestionar múltiples tipos de tokens asociados a distintas partes de cada proyecto inmobiliario, soportando flujos de inversión conectados a billeteras descentralizadas.',
        imageAfter: _asset('assets/works/brikka/05.png'),
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Traditional real estate investments require high capital and intermediary processes. At the same time, many developments require financing to move forward. Brikka addresses this by enabling projects to raise capital through tokenization, making investments accessible to a wider range of investors.',
        textEs: 'Las inversiones inmobiliarias tradicionales requieren alto capital y procesos intermediarios. Al mismo tiempo, muchos desarrollos necesitan financiamiento para avanzar. Brikka aborda esto permitiendo que los proyectos recauden capital a través de la tokenización, haciendo las inversiones accesibles a un rango más amplio de inversores.',
        imageAfter: _asset('assets/works/brikka/04.png'),
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'Users can explore projects, simulate returns, connect their wallet, and invest directly within the platform. An administrative dashboard allows developers to upload projects, configure tokens, and manage investment parameters.',
        textEs: 'Los usuarios pueden explorar proyectos, simular retornos, conectar su billetera e invertir directamente dentro de la plataforma. Un panel administrativo permite a los desarrolladores subir proyectos, configurar tokens y gestionar los parámetros de inversión.',
        imageAfter: _asset('assets/works/brikka/03.png'),
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'A functional MVP of a real estate tokenization platform was delivered and prepared for validation. Although the client decided to pause the project due to changes in the economic environment, the product remained ready for further validation and potential launch.',
        textEs: 'Se entregó un MVP funcional de una plataforma de tokenización inmobiliaria preparada para validación. Aunque el cliente decidió pausar el proyecto por cambios en el entorno económico, el producto quedó listo para validación adicional y un potencial lanzamiento.',
        imageAfter: _asset('assets/works/brikka/06.png'),
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Art Direction'],
    deliverablesEs: ['Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Prototipo', 'Sistema de diseño', 'Dirección de arte'],
    prev: 'thinknube-ai',
    next: 'carla',
  },
  {
    id: 'carla',
    num: '07',
    title: 'Car.la',
    subtitle:   'AI-Powered Assistant for Auto Repair Shops',
    subtitleEs: 'Asistente con IA para Talleres Mecánicos',
    category:   'AI Product Design · Automotive SaaS · Conversational UI',
    categoryEs: 'Diseño de Producto con IA · SaaS Automotriz · UI Conversacional',
    client: 'Car.la',
    type:   'SaaS Platform + WhatsApp Agent',
    typeEs: 'Plataforma SaaS + Agente de WhatsApp',
    duration: '~3 months',
    durationEs: '~3 meses',
    status: 'Completed',
    tag: 'AI',
    tagHighlight: true,
    cover: null,
    sections: [
      {
        label: null, labelEs: null,
        text: 'Car.la is an AI-powered platform that operates on two levels: as a customer-facing assistant through WhatsApp and as an internal management system for auto repair shops. On the customer side, it handles inquiries, schedules appointments, sends quotes, collects feedback, and runs promotional campaigns. On the business side, it organizes incoming information, manages scheduling, clients and services, and provides an internal conversational assistant for business management.',
        textEs: 'Car.la es una plataforma con IA que opera en dos niveles: como asistente de cara al cliente a través de WhatsApp y como sistema de gestión interno para talleres mecánicos. Del lado del cliente, gestiona consultas, programa turnos, envía presupuestos, recopila feedback y ejecuta campañas promocionales. Del lado del negocio, organiza la información entrante, gestiona agendas, clientes y servicios, y provee un asistente conversacional interno para la gestión del negocio.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I designed the full product experience including the landing page, logo design, conversational flows for the AI agent, and the internal dashboard used by shop staff to manage clients and services.',
        textEs: 'Diseñé la experiencia completa del producto, incluyendo la landing page, diseño del logo, flujos conversacionales para el agente de IA y el panel interno utilizado por el personal del taller para gestionar clientes y servicios.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'To create a simple AI tool that allows small auto shops to automate customer management without complex software. The design focused on making advanced AI capabilities feel approachable for non-technical users.',
        textEs: 'Crear una herramienta de IA simple que permita a los talleres pequeños automatizar la gestión de clientes sin software complejo. El diseño se centró en hacer que las capacidades avanzadas de IA se sientan accesibles para usuarios no técnicos.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'Designing a system that combines a customer-facing conversational assistant with an internal management platform while maintaining clarity across both layers. It was also necessary to structure multiple types of requests, operations, and data into a simple and usable experience.',
        textEs: 'Diseñar un sistema que combine un asistente conversacional de cara al cliente con una plataforma de gestión interna, manteniendo claridad en ambas capas. También fue necesario estructurar múltiples tipos de solicitudes, operaciones y datos en una experiencia simple y usable.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Many small auto repair shops lack dedicated administrative staff. Mechanics or owners must handle customer communication, scheduling, and business operations simultaneously. This leads to disorganized information, missed opportunities, and slow response times.',
        textEs: 'Muchos talleres mecánicos pequeños carecen de personal administrativo dedicado. Los mecánicos o dueños deben manejar la comunicación con los clientes, la agenda y las operaciones del negocio al mismo tiempo. Esto lleva a información desorganizada, oportunidades perdidas y tiempos de respuesta lentos.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The system is designed to reduce operational workload by automating customer communication and centralizing business management. It handles inquiries, generates quotes, manages scheduling, sends reminders and promotions, and allows business owners to access information through an internal conversational assistant.',
        textEs: 'El sistema está diseñado para reducir la carga operativa automatizando la comunicación con los clientes y centralizando la gestión del negocio. Gestiona consultas, genera presupuestos, administra agendas, envía recordatorios y promociones, y permite a los dueños acceder a la información a través de un asistente conversacional interno.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'The result was the complete design of the Car.la platform, including the landing page, visual identity (logo), conversational agent, and operational dashboard for auto repair shops.',
        textEs: 'El resultado fue el diseño completo de la plataforma Car.la, incluyendo la landing page, identidad visual (logo), agente conversacional y panel operativo para talleres mecánicos.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['Brand Identity', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Conversation Flows', 'Prototype'],
    deliverablesEs: ['Identidad de marca', 'Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Flujos conversacionales', 'Prototipo'],
    prev: 'brikka',
    next: 'kordiis',
  },
  {
    id: 'kordiis',
    num: '08',
    title: 'Kordiis',
    subtitle:   'Passive Safety Recording App for Critical Moments',
    subtitleEs: 'App de Grabación Pasiva para Momentos Críticos',
    category:   'Mobility · Safety Tech · Mobile App',
    categoryEs: 'Movilidad · Tecnología de Seguridad · App Móvil',
    client: 'Kordiis',
    type:   'iOS & Android App',
    typeEs: 'App iOS & Android',
    duration: '~4 months',
    durationEs: '~4 meses',
    status: 'Completed',
    tag: 'Mobile',
    tagHighlight: false,
    cover: null,
    sections: [
      {
        label: null, labelEs: null,
        text: 'Kordiis is a mobile app that records critical moments using phone sensors. It detects anomalies such as sudden speed or movement changes and triggers emergency events. When triggered, the app records video, alerts emergency contacts, and can notify nearby users.',
        textEs: 'Kordiis es una app móvil que registra momentos críticos usando los sensores del teléfono. Detecta anomalías como cambios bruscos de velocidad o movimiento y activa eventos de emergencia. Al activarse, la app graba video, alerta a los contactos de emergencia y puede notificar a usuarios cercanos.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I designed the complete product experience including mobile UI, sensor event logic, and brand identity. The focus was on creating a passive, always-on experience that feels trustworthy and unobtrusive in daily use.',
        textEs: 'Diseñé la experiencia completa del producto, incluyendo la UI móvil, la lógica de eventos por sensores y la identidad de marca. El foco fue crear una experiencia pasiva y siempre activa que se sienta confiable y discreta en el uso cotidiano.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'To create a tool capable of automatically capturing critical moments for personal safety and legal evidence. The vision was a passive safety layer that works without requiring user intervention.',
        textEs: 'Crear una herramienta capaz de capturar automáticamente momentos críticos para seguridad personal y evidencia legal. La visión era una capa de seguridad pasiva que funcione sin requerir intervención del usuario.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'One of the main challenges was designing a passive recording feature capable of retrieving up to one minute prior to the event without audio due to privacy constraints. This feature needed to be optional and user-configurable while balancing safety, privacy, and system performance.',
        textEs: 'Uno de los principales desafíos fue diseñar una función de grabación pasiva capaz de recuperar hasta un minuto previo al evento sin audio por restricciones de privacidad. Esta función debía ser opcional y configurable por el usuario, equilibrando seguridad, privacidad y rendimiento del sistema.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Many incidents occur without users being able to react quickly enough to record evidence. Traditional recording apps require active user intervention, making them useless in emergency situations.',
        textEs: 'Muchos incidentes ocurren sin que los usuarios puedan reaccionar a tiempo para registrar evidencia. Las apps de grabación tradicionales requieren intervención activa del usuario, lo que las hace inútiles en situaciones de emergencia.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The app continuously records video in the background and automatically saves the minute prior to an event. Users can configure sensitivity, emergency contacts, and notification preferences from a simple settings interface.',
        textEs: 'La app graba video continuamente en segundo plano y guarda automáticamente el minuto previo a un evento. Los usuarios pueden configurar la sensibilidad, contactos de emergencia y preferencias de notificación desde una interfaz de ajustes simple.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'A complete passive event capture system with emergency alerts and video storage was designed. The product includes both mobile and Apple Watch interfaces for maximum accessibility.',
        textEs: 'Se diseñó un sistema completo de captura pasiva de eventos con alertas de emergencia y almacenamiento de video. El producto incluye interfaces tanto para móvil como para Apple Watch para máxima accesibilidad.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['Brand Identity', 'UX Research', 'Wireframes', 'Mobile UI', 'Prototype', 'Design System'],
    deliverablesEs: ['Identidad de marca', 'Investigación UX', 'Wireframes', 'UI Móvil', 'Prototipo', 'Sistema de diseño'],
    prev: 'carla',
    next: 'off-the-grid',
  },
  {
    id: 'off-the-grid',
    num: '09',
    title: 'Off the Grid',
    subtitle:   'Social Travel App for Connecting Travelers Across Routes',
    subtitleEs: 'App de Viaje Social para Conectar Viajeros en Ruta',
    category:   'Mobile Product Design · Travel Tech · Social Network',
    categoryEs: 'Diseño de Producto Móvil · Tecnología de Viaje · Red Social',
    client: 'Off the Grid',
    type:   'iOS & Android App',
    typeEs: 'App iOS & Android',
    duration: '~3 months',
    durationEs: '~3 meses',
    status: 'Completed',
    tag: 'Travel',
    tagHighlight: false,
    cover: null,
    sections: [
      {
        label: null, labelEs: null,
        text: 'Off the Grid is a mobile application designed to connect travelers who share similar routes or destinations. The platform allows users to plan trips, discover itineraries, connect with other travelers, and participate in activities together. Unlike traditional travel planning tools, the product focuses on social interaction between travelers. The platform also integrates an AI travel planner capable of suggesting itineraries, destinations, and activities based on user preferences.',
        textEs: 'Off the Grid es una aplicación móvil diseñada para conectar viajeros que comparten rutas o destinos similares. La plataforma permite a los usuarios planificar viajes, descubrir itinerarios, conectarse con otros viajeros y participar en actividades juntos. A diferencia de las herramientas de planificación de viajes tradicionales, el producto se centra en la interacción social entre viajeros. La plataforma también integra un planificador de viajes con IA capaz de sugerir itinerarios, destinos y actividades según las preferencias del usuario.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: "My role focused on interaction design and high-fidelity prototyping, defining how users would move through the product while balancing the platform's different layers: travel planning, social discovery, and user-generated content. The goal was to create a navigation structure where these features could coexist naturally.",
        textEs: 'Mi rol se centró en el diseño de interacción y el prototipado de alta fidelidad, definiendo cómo los usuarios navegarían el producto mientras se equilibraban las distintas capas de la plataforma: planificación de viajes, descubrimiento social y contenido generado por usuarios. El objetivo era crear una estructura de navegación donde estas funciones pudieran coexistir naturalmente.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The vision was to transform travel planning into a social experience. Instead of exploring destinations individually, users could discover places and activities through other travelers in the same location.',
        textEs: 'La visión era transformar la planificación de viajes en una experiencia social. En lugar de explorar destinos individualmente, los usuarios podían descubrir lugares y actividades a través de otros viajeros en la misma ubicación.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: "One of the main challenges was defining the platform's navigation structure while balancing three layers: social discovery, travel planning tools, and user-generated content. The original concept included a gamification system based on coins that could unlock hidden information about locations, which proved technically complex in remote areas.",
        textEs: 'Uno de los principales desafíos fue definir la estructura de navegación de la plataforma equilibrando tres capas: descubrimiento social, herramientas de planificación de viajes y contenido generado por usuarios. El concepto original incluía un sistema de gamificación basado en monedas para desbloquear información oculta sobre lugares, lo que resultó técnicamente complejo en zonas remotas.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Traditional travel apps focus on individual planning and rarely facilitate meaningful connections between travelers who share similar destinations or routes.',
        textEs: 'Las apps de viaje tradicionales se enfocan en la planificación individual y rara vez facilitan conexiones significativas entre viajeros que comparten destinos o rutas similares.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The product evolved toward map-based social discovery, group activities, and safer connection mechanisms. To maintain safety, the platform requires mutual acceptance before enabling chat or participation in activities.',
        textEs: 'El producto evolucionó hacia el descubrimiento social basado en mapas, actividades grupales y mecanismos de conexión más seguros. Para mantener la seguridad, la plataforma requiere aceptación mutua antes de habilitar el chat o la participación en actividades.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: "The project resulted in a fully navigable MVP prototype that allowed the client to validate the concept and explore future development directions. One key insight was reconsidering the original monetization strategy and strengthening the product's core value: connecting travelers and enabling shared experiences.",
        textEs: 'El proyecto resultó en un prototipo MVP completamente navegable que permitió al cliente validar el concepto y explorar direcciones futuras de desarrollo. Un insight clave fue reconsiderar la estrategia de monetización original y fortalecer el valor central del producto: conectar viajeros y habilitar experiencias compartidas.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['UX Research', 'Interaction Design', 'Wireframes', 'High-fidelity UI', 'Prototype'],
    deliverablesEs: ['Investigación UX', 'Diseño de interacción', 'Wireframes', 'UI de alta fidelidad', 'Prototipo'],
    prev: 'kordiis',
    next: 'whasi',
  },
  {
    id: 'whasi',
    num: '10',
    title: 'Whasi',
    subtitle:   'AI Business Assistant for Small Businesses via WhatsApp',
    subtitleEs: 'Asistente de Negocio con IA para PYMEs vía WhatsApp',
    category:   'AI Product Design · SMB SaaS · Conversational UI',
    categoryEs: 'Diseño de Producto con IA · SaaS PYME · UI Conversacional',
    client: 'Whasi',
    type:   'SaaS Platform + WhatsApp Agent',
    typeEs: 'Plataforma SaaS + Agente de WhatsApp',
    duration: '~4 months',
    durationEs: '~4 meses',
    status: 'In Progress',
    tag: 'AI',
    tagHighlight: true,
    cover: null,
    sections: [
      {
        label: null, labelEs: null,
        text: 'Whasi is an AI-powered business assistant designed to help small businesses manage customer communication primarily through WhatsApp. The system automates responses, appointment scheduling, payments, and message filtering using two complementary AI agents: an internal assistant for the business owner and a customer-facing assistant.',
        textEs: 'Whasi es un asistente de negocio con IA diseñado para ayudar a pequeñas empresas a gestionar la comunicación con sus clientes principalmente a través de WhatsApp. El sistema automatiza respuestas, programación de citas, pagos y filtrado de mensajes usando dos agentes de IA complementarios: un asistente interno para el dueño del negocio y un asistente de cara al cliente.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH', labelEs: 'MI ENFOQUE',
        text: 'I designed the complete product experience including the application interface, user flows, the AI-powered messaging management system, the marketing website, and the brand identity.',
        textEs: 'Diseñé la experiencia completa del producto, incluyendo la interfaz de la aplicación, flujos de usuario, el sistema de gestión de mensajes con IA, el sitio de marketing y la identidad de marca.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION', labelEs: 'VISIÓN E INTENCIÓN',
        text: 'The goal was to create a simple AI layer that allows small businesses to manage large volumes of customer messages without complex software. Making advanced AI capabilities accessible to non-technical business owners.',
        textEs: 'El objetivo era crear una capa de IA simple que permita a las pequeñas empresas gestionar grandes volúmenes de mensajes de clientes sin software complejo. Hacer que las capacidades avanzadas de IA sean accesibles para dueños de negocios no técnicos.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE', labelEs: 'DESAFÍO',
        text: 'The main challenge was designing a lightweight product capable of integrating with existing messaging ecosystems while remaining easy to deploy and manage for non-technical users.',
        textEs: 'El principal desafío fue diseñar un producto ligero capaz de integrarse con ecosistemas de mensajería existentes, manteniéndose fácil de implementar y gestionar para usuarios no técnicos.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM', labelEs: 'PROBLEMA',
        text: 'Many small businesses manage customer communication manually, resulting in lost time and missed opportunities. The same person handles customer inquiries, scheduling, and operations simultaneously.',
        textEs: 'Muchas pequeñas empresas gestionan la comunicación con los clientes de forma manual, lo que resulta en tiempo perdido y oportunidades desaprovechadas. La misma persona maneja consultas de clientes, agendas y operaciones simultáneamente.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN', labelEs: 'DISEÑO CENTRADO EN EL USUARIO',
        text: 'The product enables business owners to control conversations, automations, and AI responses through a clear and simple interface. Two AI agents work in parallel — one visible to customers, one internal for the business owner.',
        textEs: 'El producto permite a los dueños de negocios controlar conversaciones, automatizaciones y respuestas de IA a través de una interfaz clara y simple. Dos agentes de IA trabajan en paralelo: uno visible para los clientes y uno interno para el dueño del negocio.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS', labelEs: 'RESULTADOS CLAVE',
        text: 'The project produced a full product prototype and brand system positioning Whasi as a friendly and practical AI assistant for businesses. The product is currently in development and preparing for its first public release.',
        textEs: 'El proyecto produjo un prototipo completo del producto y un sistema de marca que posiciona a Whasi como un asistente de IA amigable y práctico para negocios. El producto está actualmente en desarrollo y preparando su primer lanzamiento público.',
        imageAfter: null,
      },
    ],
    role:   'Product Designer',
    roleEs: 'Diseñador de Producto',
    deliverables:   ['Brand Identity', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Conversation Flows', 'Marketing Website'],
    deliverablesEs: ['Identidad de marca', 'Investigación UX', 'Wireframes', 'UI de alta fidelidad', 'Flujos conversacionales', 'Sitio de marketing'],
    prev: 'off-the-grid',
    next: null,
  },
];
