// ─────────────────────────────────────────────
//  ALEJANDRO ARAB — CMS DE PROYECTOS
//  Editá este archivo para actualizar el sitio.
//  imageAfter: URL de imagen que aparece DESPUÉS de esa sección
//  imageAfter: null → no hay imagen después de esa sección
// ─────────────────────────────────────────────

// Resolve local asset paths regardless of whether we're at root or works/
const _BASE = window.location.pathname.includes('/works/') ? '../' : '';
function _asset(path) { return path.startsWith('http') ? path : _BASE + path; }

const PROJECTS = [
  {
    id: 'fan-raise',
    num: '01',
    title: 'Fan Raise',
    subtitle: 'Web & Mobile App for Sports-Based Fundraising',
    category: 'Product Design · Sports Tech · Fundraising',
    client: 'FanRaise',
    type: 'Web & Mobile App',
    duration: '~4 months',
    status: 'Completed',
    tag: 'Sports Tech',
    tagHighlight: true,
    cover: 'https://framerusercontent.com/images/a76GME8gBeF4fUWSagVlJtWQE4.png',
    sections: [
      {
        label: null,
        text: 'FanRaise is a web and mobile platform that enables nonprofit organizations to raise funds through sports engagement. Fans participate by making pledge-based donations tied to predictions about sports events. If the prediction is correct, the user fulfills their pledge and can participate in prize draws or rewards. The platform connects organizations, athletes, teams, and fans in an experience that blends sports entertainment with social impact.',
        imageAfter: 'https://framerusercontent.com/images/a76GME8gBeF4fUWSagVlJtWQE4.png',
      },
      {
        label: 'MY APPROACH',
        text: 'I led the full product design process from early strategic discussions to high-fidelity prototypes. The goal was to create a simple experience that combines sports predictions, donations, and gamification. I also designed the visual identity and logo of the product, aligning the brand with the emotional and participatory tone of the experience. Flows were designed both for fans participating in events and for organizations creating fundraising campaigns.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'The vision was to transform how fans support social causes by leveraging the excitement of sports. Instead of passive donations, users actively participate by predicting sports outcomes. This creates a more engaging and emotional fundraising experience that connects entertainment with social impact.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'One of the main challenges was designing a system that combines multiple mechanics: sports predictions, pledge donations, rewards, and event management. The interface needed to keep the experience simple while supporting these complex interactions.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Nonprofit organizations often struggle to maintain long-term donor engagement. Traditional fundraising campaigns rely on direct donations that can feel passive to younger audiences. FanRaise addresses this by turning donations into an interactive experience tied to sports events.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'Users can explore sports events, select a prediction, and choose a pledge donation amount. If the prediction is correct, the pledged donation is completed. Organizations and teams can create events, define participation rules, and monitor results through dedicated dashboards.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'The result was a fully designed web and mobile platform for sports-based fundraising. Product flows include event discovery, predictions, donations, and campaign management. The project demonstrates how sports engagement can create new forms of social participation and fundraising.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Brand Identity'],
    prev: null,
    next: 'rockmap',
  },
  {
    id: 'rockmap',
    num: '02',
    title: 'RockMap',
    subtitle: 'Mobile App for Discovering Rock Culture Across Europe',
    category: 'Mobile Product Design · Music Discovery · Social',
    client: 'Concept Project',
    type: 'iOS & Android App',
    duration: '2024',
    status: 'Completed',
    tag: 'Mobile',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/hFrX1T4nGkqzEovF9bhl1fjyqE8.png',
    sections: [
      {
        label: null,
        text: 'Rockmap is a mobile app designed for rock fans traveling across Europe who want to discover bars, concerts, and music venues. The platform combines travel, music discovery, and community into a unique cultural experience.',
        imageAfter: 'https://framerusercontent.com/images/hFrX1T4nGkqzEovF9bhl1fjyqE8.png',
      },
      {
        label: 'MY APPROACH',
        text: 'The product experience was centered around a map interface for discovering music venues and fans nearby. The design prioritized discovery, simplicity, and community — building a sense of belonging around shared musical passion.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'To combine travel, music, and community into a unique discovery experience. The vision was to create the definitive guide to rock culture in Europe — a living map built and maintained by the community.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'Integrating Spotify data, events, and geolocation into a cohesive experience. The main challenge was balancing the complexity of a map-based interface with the simplicity required for a community app.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Travelers rely on fragmented sources to discover local music experiences. There was no single platform connecting rock culture, venues, and fans across European cities.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The app allows users to explore venues, artists, and community through a map-centered interface. Users can discover local scenes, follow artists, and connect with other rock fans in the same city.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'A complete mobile product concept for location-based music discovery was designed. The product was built with scalability in mind, supporting multiple cities and countries while maintaining a consistent community feel.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['UX Research', 'Wireframes', 'Mobile UI', 'Prototype', 'Design System'],
    prev: 'fan-raise',
    next: 'tickit-clubes',
  },
  {
    id: 'tickit-clubes',
    num: '03',
    title: 'Tickit Clubes',
    subtitle: 'Digital Membership and Ticketing Platform for Sports Clubs',
    category: 'Product Design · Sports Tech · Ticketing',
    client: 'Tickit',
    type: 'Web & Mobile Platform',
    duration: '2024–2025',
    status: 'Completed',
    tag: 'Sports Tech',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/YjO3t9fDkTY1CzeU93Be7O5iqw.png',
    sections: [
      {
        label: null,
        text: 'Tickit Clubes is a platform designed for sports clubs that digitalizes membership management, ticket sales, and exclusive content. It enables clubs to manage members, sell tickets, and offer digital benefits through a centralized experience. The solution combines ticketing, digital identity, and content into a single platform accessible via mobile or web.',
        imageAfter: 'https://framerusercontent.com/images/YjO3t9fDkTY1CzeU93Be7O5iqw.png',
      },
      {
        label: 'MY APPROACH',
        text: 'I designed the full product experience including user flows, mobile and web UI, digital membership systems, and event management. The goal was to create a flexible platform adaptable to different clubs while maintaining identity and customization.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'The vision was to transform the relationship between clubs and fans through a unified digital experience combining membership, content, and events. Moving from physical cards and manual processes to a fully digital ecosystem.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'A key challenge was adapting a general ticketing platform to the specific needs of sports clubs, including customization, identity, and content management. Designing for two very different user types — administrators and fans — within a single coherent product.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Clubs often manage memberships, ticketing, and fan communication through disconnected systems. This fragmentation leads to poor fan experience and operational inefficiency.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'Users can access their digital membership, purchase tickets, explore exclusive content, and manage their relationship with the club from a single app. Club administrators get a dedicated dashboard to manage operations independently.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'A modular platform was designed enabling clubs to digitalize their ecosystem and enhance fan experience. The product was adopted by multiple clubs across Latin America.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['Product Strategy', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Design System'],
    prev: 'rockmap',
    next: 'tickit',
  },
  {
    id: 'tickit',
    num: '04',
    title: 'Tickit',
    subtitle: 'Event Ticketing Platform for General and Sports Events',
    category: 'Product Design · Event Tech · Ticketing',
    client: 'Tickit',
    type: 'Web & Mobile Platform',
    duration: '2024–2025',
    status: 'Completed',
    tag: 'Ticketing',
    tagHighlight: false,
    cover: 'https://framerusercontent.com/images/FATuDnHFj0egSso4TOCh8lBTWo.png',
    sections: [
      {
        label: null,
        text: 'Tickit is a digital ticketing platform designed to manage events of all kinds, from concerts to sports events. It allows organizers to create, manage, and sell tickets while users can discover events and purchase tickets easily.',
        imageAfter: 'https://framerusercontent.com/images/FATuDnHFj0egSso4TOCh8lBTWo.png',
      },
      {
        label: 'MY APPROACH',
        text: 'I designed the full product experience including user flows, UI, event management system, and the visual identity and branding of the product. The approach centered around reducing steps from event discovery to ticket purchase while building trust through transparent pricing.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'To create a scalable platform that simplifies event management and enhances the ticket purchasing experience. The vision was to make ticketing feel as fast and intuitive as the best consumer apps.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'The main challenge was designing a flexible experience that works across different event types while maintaining simplicity and speed. The system needed to handle high-traffic moments — popular events that sell out in minutes.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Many ticketing systems are complex and unintuitive for both organizers and users. Hidden fees and friction in the purchase flow cause drop-offs and poor fan experience.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The platform allows users to explore events, purchase tickets, and manage access easily, while providing organizers with tools to manage events, track sales, and engage fans.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'A complete ticketing platform was designed with a focus on usability, scalability, and consistent branding. The product was launched and used for multiple sporting and entertainment events across Latin America.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Brand Identity'],
    prev: 'tickit-clubes',
    next: 'thinknube-ai',
  },
  {
    id: 'thinknube-ai',
    num: '05',
    title: 'Thinknube.AI',
    subtitle: 'AI-Powered Market Research SaaS Platform',
    category: 'AI Product Design · SaaS · Market Research',
    client: 'Nube Research',
    type: 'SaaS Web Application',
    duration: '~4 months',
    status: 'Completed',
    tag: 'AI',
    tagHighlight: true,
    cover: 'https://framerusercontent.com/images/GTlAkYEFQUj3n4lUszhPXFH0yCQ.png',
    sections: [
      {
        label: null,
        text: 'ThinkNube is an AI-powered market research SaaS platform developed by Nube Research. The platform allows companies to create conversational research studies using an AI agent that interviews participants through channels such as WhatsApp, Instagram, or direct links. The product automates processes that traditionally require research agencies, manual interviews, and long analysis cycles. Teams can design studies, reach participants, and analyze insights within a single platform.',
        imageAfter: 'https://framerusercontent.com/images/GTlAkYEFQUj3n4lUszhPXFH0yCQ.png',
      },
      {
        label: 'MY APPROACH',
        text: 'The approach focused on balancing AI automation with a clear and intuitive user experience. Product flows were designed for study creation, audience segmentation, and insights analysis. I worked on product architecture, study creation flows, dashboard design, and the overall visual direction of the platform.',
        imageAfter: 'https://framerusercontent.com/images/3NhVOlvcUCfwBuuMGVRxNO08uTw.png',
      },
      {
        label: 'VISION & INTENTION',
        text: 'The vision was to democratize access to market research, enabling companies of any size to gather real user insights quickly without relying on traditional agencies. The design focused on clarity, professionalism, and trust while maintaining the simplicity of a modern SaaS platform.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'A key challenge was structuring complex research parameters such as segmentation, quotas, and response validation into a simple configuration flow. The platform needed to manage multiple variables within a single experience without overwhelming users.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Companies often rely on expensive research agencies or data-only tools that lack real interaction with consumers. ThinkNube addresses this by combining artificial intelligence with real consumer interviews.',
        imageAfter: 'https://framerusercontent.com/images/15uAupttQe5myjZBb54CGZQ5J2I.png',
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'Users can define objectives, select audiences, configure parameters, and monitor responses in real time. Quality control tools help detect unreliable answers. The system also includes response quality monitoring and analytics dashboards.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'The result was a solid MVP of an AI-powered research platform capable of automating interviews and generating structured insights. The product combines automation with a human-centered approach, using AI to facilitate research while preserving real consumer feedback.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['Product Strategy', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Design System', 'Prototype'],
    prev: 'tickit',
    next: 'brikka',
  },
  {
    id: 'brikka',
    num: '06',
    title: 'Brikka',
    subtitle: 'Web3 Real Estate Tokenization Platform',
    category: 'Web3 Product Design · Fintech · Real Estate',
    client: 'Real Estate Development Company',
    type: 'Web3 Platform',
    duration: '~3 months',
    status: 'Completed',
    tag: 'Web3',
    tagHighlight: true,
    cover: _asset('assets/covers/brikka.png'),
    sections: [
      {
        label: null,
        text: 'Brikka is a blockchain-based platform that enables tokenization of real estate projects. It connects developers seeking funding with investors who want to participate through digital assets. Users can invest in different components of a construction project represented as tokens, allowing participation with different levels of capital.',
        imageAfter: _asset('assets/covers/brikka.png'),
      },
      {
        label: 'MY APPROACH',
        text: 'The full product experience was designed including the landing page, investor platform, and project management dashboard. The goal was to structure complex processes — token creation, investment simulation, and wallet management — into an intuitive and understandable experience.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'The goal was to democratize real estate investing by allowing participation with smaller capital through tokenization. The design focused on communicating security, transparency, and control over investments.',
        imageAfter: 'https://framerusercontent.com/images/liNNBrAdE35OKheQRLdrQVG0Sg.png',
      },
      {
        label: 'CHALLENGE',
        text: 'A major challenge was integrating decentralized wallets and multiple token types into clear investment flows. The system needed to manage multiple token types associated with different parts of each real estate project while supporting investment flows connected to decentralized wallets.',
        imageAfter: 'https://framerusercontent.com/images/u102pLk3RzhlCDBrvMjyLOSHdQ.png',
      },
      {
        label: 'PROBLEM',
        text: 'Traditional real estate investments require high capital and intermediary processes. At the same time, many developments require financing to move forward. Brikka addresses this by enabling projects to raise capital through tokenization, making investments accessible to a wider range of investors.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'Users can explore projects, simulate returns, connect their wallet, and invest directly within the platform. An administrative dashboard allows developers to upload projects, configure tokens, and manage investment parameters.',
        imageAfter: 'https://framerusercontent.com/images/8LhRRVyZwew60fvvhIuBafes.png',
      },
      {
        label: 'KEY RESULTS',
        text: 'A functional MVP of a real estate tokenization platform was delivered and prepared for validation. Although the client decided to pause the project due to changes in the economic environment, the product remained ready for further validation and potential launch.',
        imageAfter: 'https://framerusercontent.com/images/glPoob7Q3XZzHJ1OWixiDrixxM.png',
      },
    ],
    role: 'Product Designer',
    deliverables: ['UX Research', 'Wireframes', 'High-fidelity UI', 'Prototype', 'Design System', 'Art Direction'],
    prev: 'thinknube-ai',
    next: 'carla',
  },
  {
    id: 'carla',
    num: '07',
    title: 'Car.la',
    subtitle: 'AI-Powered Assistant for Auto Repair Shops',
    category: 'AI Product Design · Automotive SaaS · Conversational UI',
    client: 'Car.la',
    type: 'SaaS Platform + WhatsApp Agent',
    duration: '~3 months',
    status: 'Completed',
    tag: 'AI',
    tagHighlight: true,
    cover: null,
    sections: [
      {
        label: null,
        text: 'Car.la is an AI-powered platform that operates on two levels: as a customer-facing assistant through WhatsApp and as an internal management system for auto repair shops. On the customer side, it handles inquiries, schedules appointments, sends quotes, collects feedback, and runs promotional campaigns. On the business side, it organizes incoming information, manages scheduling, clients and services, and provides an internal conversational assistant for business management.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH',
        text: 'I designed the full product experience including the landing page, logo design, conversational flows for the AI agent, and the internal dashboard used by shop staff to manage clients and services.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'To create a simple AI tool that allows small auto shops to automate customer management without complex software. The design focused on making advanced AI capabilities feel approachable for non-technical users.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'Designing a system that combines a customer-facing conversational assistant with an internal management platform while maintaining clarity across both layers. It was also necessary to structure multiple types of requests, operations, and data into a simple and usable experience.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Many small auto repair shops lack dedicated administrative staff. Mechanics or owners must handle customer communication, scheduling, and business operations simultaneously. This leads to disorganized information, missed opportunities, and slow response times.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The system is designed to reduce operational workload by automating customer communication and centralizing business management. It handles inquiries, generates quotes, manages scheduling, sends reminders and promotions, and allows business owners to access information through an internal conversational assistant.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'The result was the complete design of the Car.la platform, including the landing page, visual identity (logo), conversational agent, and operational dashboard for auto repair shops.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['Brand Identity', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Conversation Flows', 'Prototype'],
    prev: 'brikka',
    next: 'kordiis',
  },
  {
    id: 'kordiis',
    num: '08',
    title: 'Kordiis',
    subtitle: 'Passive Safety Recording App for Critical Moments',
    category: 'Mobility · Safety Tech · Mobile App',
    client: 'Kordiis',
    type: 'iOS & Android App',
    duration: '~4 months',
    status: 'Completed',
    tag: 'Mobile',
    tagHighlight: false,
    cover: null,
    sections: [
      {
        label: null,
        text: 'Kordiis is a mobile app that records critical moments using phone sensors. It detects anomalies such as sudden speed or movement changes and triggers emergency events. When triggered, the app records video, alerts emergency contacts, and can notify nearby users.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH',
        text: 'I designed the complete product experience including mobile UI, sensor event logic, and brand identity. The focus was on creating a passive, always-on experience that feels trustworthy and unobtrusive in daily use.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'To create a tool capable of automatically capturing critical moments for personal safety and legal evidence. The vision was a passive safety layer that works without requiring user intervention.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'One of the main challenges was designing a passive recording feature capable of retrieving up to one minute prior to the event without audio due to privacy constraints. This feature needed to be optional and user-configurable while balancing safety, privacy, and system performance.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Many incidents occur without users being able to react quickly enough to record evidence. Traditional recording apps require active user intervention, making them useless in emergency situations.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The app continuously records video in the background and automatically saves the minute prior to an event. Users can configure sensitivity, emergency contacts, and notification preferences from a simple settings interface.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'A complete passive event capture system with emergency alerts and video storage was designed. The product includes both mobile and Apple Watch interfaces for maximum accessibility.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['Brand Identity', 'UX Research', 'Wireframes', 'Mobile UI', 'Prototype', 'Design System'],
    prev: 'carla',
    next: 'off-the-grid',
  },
  {
    id: 'off-the-grid',
    num: '09',
    title: 'Off the Grid',
    subtitle: 'Social Travel App for Connecting Travelers Across Routes',
    category: 'Mobile Product Design · Travel Tech · Social Network',
    client: 'Off the Grid',
    type: 'iOS & Android App',
    duration: '~3 months',
    status: 'Completed',
    tag: 'Travel',
    tagHighlight: false,
    cover: null,
    sections: [
      {
        label: null,
        text: 'Off the Grid is a mobile application designed to connect travelers who share similar routes or destinations. The platform allows users to plan trips, discover itineraries, connect with other travelers, and participate in activities together. Unlike traditional travel planning tools, the product focuses on social interaction between travelers. The platform also integrates an AI travel planner capable of suggesting itineraries, destinations, and activities based on user preferences.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH',
        text: 'My role focused on interaction design and high-fidelity prototyping, defining how users would move through the product while balancing the platform\'s different layers: travel planning, social discovery, and user-generated content. The goal was to create a navigation structure where these features could coexist naturally.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'The vision was to transform travel planning into a social experience. Instead of exploring destinations individually, users could discover places and activities through other travelers in the same location.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'One of the main challenges was defining the platform\'s navigation structure while balancing three layers: social discovery, travel planning tools, and user-generated content. The original concept included a gamification system based on coins that could unlock hidden information about locations, which proved technically complex in remote areas.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Traditional travel apps focus on individual planning and rarely facilitate meaningful connections between travelers who share similar destinations or routes.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The product evolved toward map-based social discovery, group activities, and safer connection mechanisms. To maintain safety, the platform requires mutual acceptance before enabling chat or participation in activities.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'The project resulted in a fully navigable MVP prototype that allowed the client to validate the concept and explore future development directions. One key insight was reconsidering the original monetization strategy and strengthening the product\'s core value: connecting travelers and enabling shared experiences.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['UX Research', 'Interaction Design', 'Wireframes', 'High-fidelity UI', 'Prototype'],
    prev: 'kordiis',
    next: 'whasi',
  },
  {
    id: 'whasi',
    num: '10',
    title: 'Whasi',
    subtitle: 'AI Business Assistant for Small Businesses via WhatsApp',
    category: 'AI Product Design · SMB SaaS · Conversational UI',
    client: 'Whasi',
    type: 'SaaS Platform + WhatsApp Agent',
    duration: '~4 months',
    status: 'In Progress',
    tag: 'AI',
    tagHighlight: true,
    cover: null,
    sections: [
      {
        label: null,
        text: 'Whasi is an AI-powered business assistant designed to help small businesses manage customer communication primarily through WhatsApp. The system automates responses, appointment scheduling, payments, and message filtering using two complementary AI agents: an internal assistant for the business owner and a customer-facing assistant.',
        imageAfter: null,
      },
      {
        label: 'MY APPROACH',
        text: 'I designed the complete product experience including the application interface, user flows, the AI-powered messaging management system, the marketing website, and the brand identity.',
        imageAfter: null,
      },
      {
        label: 'VISION & INTENTION',
        text: 'The goal was to create a simple AI layer that allows small businesses to manage large volumes of customer messages without complex software. Making advanced AI capabilities accessible to non-technical business owners.',
        imageAfter: null,
      },
      {
        label: 'CHALLENGE',
        text: 'The main challenge was designing a lightweight product capable of integrating with existing messaging ecosystems while remaining easy to deploy and manage for non-technical users.',
        imageAfter: null,
      },
      {
        label: 'PROBLEM',
        text: 'Many small businesses manage customer communication manually, resulting in lost time and missed opportunities. The same person handles customer inquiries, scheduling, and operations simultaneously.',
        imageAfter: null,
      },
      {
        label: 'USER-CENTERED DESIGN',
        text: 'The product enables business owners to control conversations, automations, and AI responses through a clear and simple interface. Two AI agents work in parallel — one visible to customers, one internal for the business owner.',
        imageAfter: null,
      },
      {
        label: 'KEY RESULTS',
        text: 'The project produced a full product prototype and brand system positioning Whasi as a friendly and practical AI assistant for businesses. The product is currently in development and preparing for its first public release.',
        imageAfter: null,
      },
    ],
    role: 'Product Designer',
    deliverables: ['Brand Identity', 'UX Research', 'Wireframes', 'High-fidelity UI', 'Conversation Flows', 'Marketing Website'],
    prev: 'off-the-grid',
    next: null,
  },
];
